{{- if .Values.bosun.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "datarobot-management-agent.bosunServiceAccountName" . }}
  labels:
    {{- include "datarobot-management-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "datarobot-management-agent.bosunServiceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "datarobot-management-agent.bosunServiceAccountName" . }}
{{- end }}
