{{- if .Values.bosun.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "datarobot-management-agent.bosunServiceAccountName" . }}
  labels:
    {{- include "datarobot-management-agent.labels" . | nindent 4 }}
  {{- with .Values.bosun.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
