{{- if .Values.imageBuilder.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "datarobot-management-agent.kanikoServiceAccountName" . }}
  labels:
    {{- include "datarobot-management-agent.labels" . | nindent 4 }}
  {{- with .Values.imageBuilder.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
