{{- if .Values.imageBuilder.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "datarobot-management-agent.kanikoServiceAccountName" . }}
  labels:
    {{- include "datarobot-management-agent.labels" . | nindent 4 }}
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ include "datarobot-management-agent.kanikoServiceAccountName" . }}
{{- end }}
